spring:
  application:
    name: housekeeper
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USER_NAME}
    password: ${MAIL_USER_PASSWORD}
    port: 465
    protocol: "smtps"
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    time-zone: "Europe/Moscow"
    serialization:
      write_dates_as_timestamps: "false"

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    database: POSTGRESQL
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        format_sql: true
#        jdbc:
#          time_zone: "Europe/Moscow"

server:
  error:
    include-message: always
  servlet:
    context-path: "/api"

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /api/v3/api-docs
    configUrl: /api/v3/api-docs/swagger-config
    operations-sorter: alpha
  show-actuator: true

my:
  inn: ${MY_INN}
  name: ${MY_NAME}
  account: ${MY_ACCOUNT}